title: Patch Clamp Handbook
author: Lars Henrik Nelson
copyright: "2025"

exectute:
  execute_notebooks: auto
  timeout: 360

bibtex_bibfiles:
  - references.bib

sphinx:
  config:
    bibtex_reference_style: author_year